# Generated by Django 2.2.4 on 2019-09-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterData', '0001_initial'),
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expirence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=225)),
                ('company_name', models.CharField(max_length=225)),
                ('from_date', models.DateField()),
                ('is_work_there', models.BooleanField()),
                ('description', models.CharField(max_length=256)),
                ('starting_salary', models.IntegerField()),
                ('ending_salary', models.IntegerField()),
                ('career_level', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='MasterData.CurrentLevel')),
                ('company_industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MasterData.CompanyIndustry')),
                ('company_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MasterData.CompanySize')),
                ('expiernce_type', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.JobType')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MasterData.Role')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=255)),
                ('martial_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=10)),
                ('num_of_dependencies', models.IntegerField()),
                ('have_driving_license', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Intersts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MasterData.Country')),
                ('current_level', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='MasterData.CurrentLevel')),
                ('job_type', models.ManyToManyField(to='MasterData.JobType')),
                ('role', models.ManyToManyField(to='MasterData.Role')),
                ('search_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MasterData.SearchStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=256)),
                ('profiency_rate', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('years_of_expiernce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MasterData.YearsOfExpiernce')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_cv', models.FilePathField(null=True)),
                ('experiences', models.ManyToManyField(to='JobSeeker.Expirence')),
                ('general_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobSeeker.GeneralInfo')),
                ('general_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.Profile')),
                ('intersts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobSeeker.Intersts')),
                ('skills', models.ManyToManyField(to='JobSeeker.Skill')),
            ],
        ),
    ]
