# Generated by Django 2.2.4 on 2019-10-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_remove_jobpost_applicants'),
        ('JobSeeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerAndJobPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_saved', models.BooleanField(default=False)),
                ('is_applied_for', models.BooleanField(default=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job.JobPost')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobSeeker.JobSeekerProfile')),
            ],
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='jobs',
            field=models.ManyToManyField(through='JobSeeker.JobSeekerAndJobPosts', to='Job.JobPost'),
        ),
    ]
