# Generated by Django 2.2.4 on 2019-09-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='nicename',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='numcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='phonecode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expirence',
            name='expiernce_type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Part time', 'Part time'), ('Volunteering', 'Volunteering'), ('Student activity', 'Student activity'), ('Freelance/Project', 'Freelance/Project'), ('Full time', 'Full time')], max_length=25),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10),
        ),
    ]
