# Generated by Django 2.2.4 on 2019-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeeker', '0002_auto_20190909_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirence',
            name='expiernce_type',
            field=models.CharField(choices=[('Part time', 'Part time'), ('Full time', 'Full time'), ('Volunteering', 'Volunteering'), ('Student activity', 'Student activity'), ('Internship', 'Internship'), ('Freelance/Project', 'Freelance/Project')], max_length=25),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='martial_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=10),
        ),
    ]
