# Generated by Django 2.2.4 on 2019-09-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeeker', '0002_auto_20190916_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirence',
            name='expiernce_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobSeeker.JobType'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
