# Generated by Django 2.2.4 on 2019-09-17 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeeker', '0003_auto_20190917_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersts',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MasterData.Country'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
