# Generated by Django 2.2.4 on 2019-09-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterData', '0001_initial'),
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('mobile_number', models.CharField(max_length=256, null=True)),
                ('job_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MasterData.Role')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, null=True)),
                ('company_phone', models.CharField(max_length=11, null=True)),
                ('company_website', models.CharField(max_length=256, null=True)),
                ('ContactInfo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employer.ContactInfo')),
                ('company_industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MasterData.CompanyIndustry')),
                ('company_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MasterData.CompanySize')),
                ('general_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.Profile')),
            ],
        ),
    ]
