# Generated by Django 2.2.4 on 2019-09-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, null=True)),
                ('company_phone', models.CharField(max_length=11, null=True)),
                ('company_website', models.CharField(max_length=256, null=True)),
                ('company_industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Employer.CompanyIndustry')),
                ('company_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Employer.CompanySize')),
                ('general_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.Profile')),
            ],
        ),
    ]
