# Generated by Django 2.2.4 on 2019-10-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=256)),
            ],
        ),
    ]
