# Generated by Django 2.2.4 on 2019-10-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0002_language_salaryranges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryRanges',
        ),
    ]
