# Generated by Django 2.2.4 on 2019-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20190909_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
