# Generated by Django 2.2.4 on 2019-10-07 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobSeeker', '0001_initial'),
        ('MasterData', '0003_delete_salaryranges'),
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_about_job', models.BooleanField(default=True)),
                ('is_job_requirement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('points', models.ManyToManyField(to='Job.Point')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=256)),
                ('years_of_expierence', models.CharField(max_length=256)),
                ('salary', models.CharField(max_length=256)),
                ('vacancies', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('applicants', models.ManyToManyField(to='JobSeeker.JobSeekerProfile')),
                ('career_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MasterData.CurrentLevel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Employer.EmployerProfile')),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Job.JobDescription')),
                ('job_roles', models.ManyToManyField(to='MasterData.Role')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MasterData.JobType')),
                ('languages', models.ManyToManyField(to='MasterData.Language')),
            ],
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='pargraphs',
            field=models.ManyToManyField(to='Job.Paragraph'),
        ),
    ]
