# Generated by Django 2.2.4 on 2019-10-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employer', '0001_initial'),
        ('MasterData', '0003_delete_salaryranges'),
        ('JobSeeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('is_about_job', models.BooleanField(blank=True, default=True, null=True)),
                ('is_job_requirement', models.BooleanField(blank=True, default=False, null=True)),
                ('points', models.ManyToManyField(to='Job.Point')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=256)),
                ('years_of_expierence', models.CharField(blank=True, max_length=256, null=True)),
                ('salary', models.CharField(blank=True, default='Confidential', max_length=256, null=True)),
                ('vacancies', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('applicants', models.ManyToManyField(to='JobSeeker.JobSeekerProfile')),
                ('career_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MasterData.CurrentLevel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Employer.EmployerProfile')),
                ('job_roles', models.ManyToManyField(to='MasterData.Role')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MasterData.JobType')),
                ('languages', models.ManyToManyField(to='MasterData.Language')),
                ('pargraphs', models.ManyToManyField(to='Job.Paragraph')),
            ],
        ),
    ]
