# Generated by Django 2.2.4 on 2019-10-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='applicants',
        ),
    ]
