# Generated by Django 2.2.4 on 2019-11-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_remove_jobpost_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
